PLATFORMS = [
    # ─── RÉSEAUX SOCIAUX ───────────────────────────────────────────────────────
    {
        "id": "twitter",
        "name": "Twitter / X",
        "icon": "🐦",
        "cat": "RÉSEAUX SOCIAUX",
        "url": "https://x.com/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "instagram",
        "name": "Instagram",
        "icon": "📸",
        "cat": "RÉSEAUX SOCIAUX",
        "url": "https://www.instagram.com/{u}/",
        "method": "body",
        "not_found_strings": ["Sorry, this page isn't available"],
        "not_found_status": 404,
    },
    {
        "id": "facebook",
        "name": "Facebook",
        "icon": "👤",
        "cat": "RÉSEAUX SOCIAUX",
        "url": "https://www.facebook.com/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "tiktok",
        "name": "TikTok",
        "icon": "🎵",
        "cat": "RÉSEAUX SOCIAUX",
        "url": "https://www.tiktok.com/@{u}",
        "method": "body",
        "not_found_strings": ["Couldn't find this account"],
        "not_found_status": 404,
    },
    {
        "id": "linkedin",
        "name": "LinkedIn",
        "icon": "💼",
        "cat": "RÉSEAUX SOCIAUX",
        "url": "https://www.linkedin.com/in/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "pinterest",
        "name": "Pinterest",
        "icon": "📌",
        "cat": "RÉSEAUX SOCIAUX",
        "url": "https://www.pinterest.com/{u}/",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "snapchat",
        "name": "Snapchat",
        "icon": "👻",
        "cat": "RÉSEAUX SOCIAUX",
        "url": "https://www.snapchat.com/add/{u}",
        "method": "body",
        "not_found_strings": ["Sorry! Couldn't find"],
        "not_found_status": 404,
    },
    {
        "id": "medium",
        "name": "Medium",
        "icon": "✍️",
        "cat": "FORUMS / CONTENU",
        "url": "https://medium.com/@{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "tumblr",
        "name": "Tumblr",
        "icon": "🌀",
        "cat": "FORUMS / CONTENU",
        "url": "https://{u}.tumblr.com",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "patreon",
        "name": "Patreon",
        "icon": "🎨",
        "cat": "FORUMS / CONTENU",
        "url": "https://www.patreon.com/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    # ─── DEV / TECH ────────────────────────────────────────────────────────────
    {
        "id": "github",
        "name": "GitHub",
        "icon": "🐙",
        "cat": "DEV / TECH",
        "url": "https://github.com/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "gitlab",
        "name": "GitLab",
        "icon": "🦊",
        "cat": "DEV / TECH",
        "url": "https://gitlab.com/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "npm",
        "name": "npm",
        "icon": "📦",
        "cat": "DEV / TECH",
        "url": "https://www.npmjs.com/~{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "pypi",
        "name": "PyPI",
        "icon": "🐍",
        "cat": "DEV / TECH",
        "url": "https://pypi.org/user/{u}/",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "hackernews",
        "name": "Hacker News",
        "icon": "🔶",
        "cat": "DEV / TECH",
        "url": "https://news.ycombinator.com/user?id={u}",
        "method": "body",
        "not_found_strings": ["No such user"],
        "not_found_status": 404,
    },
    {
        "id": "devto",
        "name": "Dev.to",
        "icon": "👩‍💻",
        "cat": "DEV / TECH",
        "url": "https://dev.to/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "replit",
        "name": "Replit",
        "icon": "🔁",
        "cat": "DEV / TECH",
        "url": "https://replit.com/@{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    # ─── GAMING / STREAM ───────────────────────────────────────────────────────
    {
        "id": "twitch",
        "name": "Twitch",
        "icon": "🎮",
        "cat": "GAMING / STREAM",
        "url": "https://www.twitch.tv/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "youtube",
        "name": "YouTube",
        "icon": "▶️",
        "cat": "FORUMS / CONTENU",
        "url": "https://www.youtube.com/@{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "steam",
        "name": "Steam",
        "icon": "🕹️",
        "cat": "GAMING / STREAM",
        "url": "https://steamcommunity.com/id/{u}",
        "method": "body",
        "not_found_strings": ["The specified profile could not be found"],
        "not_found_status": 404,
    },
    {
        "id": "roblox",
        "name": "Roblox",
        "icon": "🧱",
        "cat": "GAMING / STREAM",
        "url": "https://www.roblox.com/users/profile?username={u}",
        "method": "body",
        "not_found_strings": ["Page Not Found", "requested page does not exist"],
        "not_found_status": 404,
    },
    {
        "id": "chess",
        "name": "Chess.com",
        "icon": "♟️",
        "cat": "GAMING / STREAM",
        "url": "https://www.chess.com/member/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "lichess",
        "name": "Lichess",
        "icon": "♞",
        "cat": "GAMING / STREAM",
        "url": "https://lichess.org/@/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "xbox",
        "name": "Xbox",
        "icon": "🎯",
        "cat": "GAMING / STREAM",
        "url": "https://xboxgamertag.com/search/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    # ─── FORUMS / CONTENU ──────────────────────────────────────────────────────
    {
        "id": "reddit",
        "name": "Reddit",
        "icon": "🤖",
        "cat": "FORUMS / CONTENU",
        "url": "https://www.reddit.com/user/{u}/about.json",
        "method": "body",
        "not_found_strings": ['"error": 404'],
        "not_found_status": 404,
    },
    # ─── ADULTE ────────────────────────────────────────────────────────────────
    {
        "id": "onlyfans",
        "name": "OnlyFans",
        "icon": "🔞",
        "cat": "FORUMS / CONTENU",
        "url": "https://onlyfans.com/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "pornhub",
        "name": "Pornhub",
        "icon": "🔥",
        "cat": "ADULTE",
        "url": "https://www.pornhub.com/model/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "cam4",
        "name": "Cam4",
        "icon": "📹",
        "cat": "ADULTE",
        "url": "https://www.cam4.com/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "stripchat",
        "name": "Stripchat",
        "icon": "💃",
        "cat": "ADULTE",
        "url": "https://stripchat.com/{u}",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
    {
        "id": "chaturbate",
        "name": "Chaturbate",
        "icon": "🎭",
        "cat": "ADULTE",
        "url": "https://chaturbate.com/{u}/",
        "method": "status",
        "not_found_strings": [],
        "not_found_status": 404,
    },
]
